apiVersion: example.com/v1
kind: Email
metadata:
  name: test-email
  namespace: default
spec:
  senderConfigRef: mailersend-config
  recipientEmail: "devinveslaw@gmail.com"
  subject: "Test Email"
  body: "This is a test email."
