# permissions for end users to view emailsenderconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emailsenderconfig-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - emailsenderconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - emailsenderconfigs/status
  verbs:
  - get
